apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed. I've taken 2 for example.
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: Knawck/nodejs-app:v1  
          ports:
            - containerPort: 3000  
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-hostname:27017/new_DB"  # Replace with MongoDB connection details
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # Replace with the desired external port
      targetPort: 3000  
  type: LoadBalancer  #[Optional But Will Use For Testing And Production Loads] Use LoadBalancer for external access, or ClusterIP for internal-only access
